/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/girls/': RouteRecordInfo<'/girls/', '/girls', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/music/': RouteRecordInfo<'/music/', '/music', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/3 - 由下到上': RouteRecordInfo<'/posts/3 - 由下到上', '/posts/3 - 由下到上', Record<never, never>, Record<never, never>>,
    '/posts/从焦虑说起': RouteRecordInfo<'/posts/从焦虑说起', '/posts/从焦虑说起', Record<never, never>, Record<never, never>>,
    '/posts/读柔石《二月》': RouteRecordInfo<'/posts/读柔石《二月》', '/posts/读柔石《二月》', Record<never, never>, Record<never, never>>,
    '/posts/揭开面纱之后': RouteRecordInfo<'/posts/揭开面纱之后', '/posts/揭开面纱之后', Record<never, never>, Record<never, never>>,
    '/posts/论迹与论心': RouteRecordInfo<'/posts/论迹与论心', '/posts/论迹与论心', Record<never, never>, Record<never, never>>,
    '/posts/瞳之crossover': RouteRecordInfo<'/posts/瞳之crossover', '/posts/瞳之crossover', Record<never, never>, Record<never, never>>,
    '/posts/我听JPOP': RouteRecordInfo<'/posts/我听JPOP', '/posts/我听JPOP', Record<never, never>, Record<never, never>>,
    '/posts/雪': RouteRecordInfo<'/posts/雪', '/posts/雪', Record<never, never>, Record<never, never>>,
    '/posts/遇见alan': RouteRecordInfo<'/posts/遇见alan', '/posts/遇见alan', Record<never, never>, Record<never, never>>,
    '/posts/kimihadouikiruka': RouteRecordInfo<'/posts/kimihadouikiruka', '/posts/kimihadouikiruka', Record<never, never>, Record<never, never>>,
    '/posts/reflection of circle-po light': RouteRecordInfo<'/posts/reflection of circle-po light', '/posts/reflection of circle-po light', Record<never, never>, Record<never, never>>,
    '/posts/testkatex': RouteRecordInfo<'/posts/testkatex', '/posts/testkatex', Record<never, never>, Record<never, never>>,
    '/Q&A/': RouteRecordInfo<'/Q&A/', '/Q&A', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
